# Push로 발동하는 Pipeline
name: "Pipeline : Push"

on:
  workflow_call:        # workflow_call 호출
    inputs:
      MODULE:           # 모듈 이름
        required: true
        type: string
      USERNAME:         # ECR 유저 이름
        required: true
        type: string
    secrets:
      AWS_ACCOUNT_ID:   # ECR 계정 ID
        required: true
      AWS_REGION:       # ECR 리전
        required: true
      IAM_ROLE:         # IAM Role Assume 권한
        required: true

jobs:
  # 변경사항 스캔
  scan-changes:
    uses: ./.github/workflows/operation_scan.yaml           # Scan Changes Workflow 호출
    with:
      MODULE: ${{ inputs.MODULE }}                          # 모듈 이름
      FIRST_COMMIT: ${{ github.event.before }}              # 푸시 이전 마지막 커밋 SHA
      LAST_COMMIT: ${{ github.event.after }}                # 푸시의 마지막 커밋 SHA
  
  # 변경사항이 있으면, 변경사항 통합
  integration:
    needs: [scan-changes]                                   # scan-changes job이 성공적으로 실행되면 integration job 실행
    if: needs.scan-changes.outputs.CHANGES_TO_MODULE > 0    # 변경사항이 있을 경우에만 실행
    uses: ./.github/workflows/operation_integration.yaml    # Integration Workflow 호출
    with:
      MODULE: ${{ inputs.MODULE }}                          # 모듈 이름
  
  # 통합 성공 시,커밋 SHA 가져오기
  get-sha:
    needs: [integration]                                    # integration job이 성공적으로 실행되면 get-sha job 실행
    uses: ./.github/workflows/operation_get_sha.yaml        # Get SHA Workflow 호출
  
  # 커밋 SHA를 태그로 하여 ECR에 배포
  ecr-deployment:
    needs: [get-sha, integration]                           # get-sha, integration job이 성공적으로 실행되면 ecr-deployment job 실행
    uses: ./.github/workflows/operation_ecr_deployment.yaml # ECR Deployment Workflow 호출
    with:
      MODULE: ${{ inputs.MODULE }}                          # 모듈 이름
      NEW_TAG: ${{ needs.get-sha.outputs.COMMIT_SHA }}      # 추가할 태그, 커밋의 SHA
      USERNAME: ${{ inputs.USERNAME }}                      # ECR 유저 이름
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}         # ECR 계정 ID
      AWS_REGION: ${{ secrets.AWS_REGION }}                 # ECR 리전
      IAM_ROLE: ${{ secrets.IAM_ROLE }}                     # IAM Role Assume 권한